name: run
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest # 运行在 ubuntu 系统环境下
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2 
        with: 
          node-version: '16.19.1'
      - name: Install Dependencies 
        run: | # `run: |` 的方式，允许我们一次定义多个要执行的命令
          yarn install
          yarn run build
      - name: Push To Pages
        working-directory: ./docs/.vitepress/dist # 指定下面指令运行的目录
        run: |
          git init
          git checkout -b main
          git add -A
          git -c user.name='贝贝' -c user.email='3188517516@qq.com' commit -m "初始化构建"
          git remote add origin https://${{secrets.TOKEN_BLOG_SITE}}@github.com/beibei/blog.git
          git push origin main -f -q
